### ISSUE TITLE
Odbijanje je dosta čudno

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-046-bilijar#4]
Napravite realnije odbijanje - na primer:

- kugle gube brzinu tokom vremena
- izracunajte ugao pod kojim treba da nastave da se krecu kugle (mozete da nadjete formule na netu, ne morate sami da ih izvodite)
- izracunajte brzinu posle odbijanja za obe kugle

**Comment by chokaa** [comment]
Namerno sam stavio da kugle gube brzinu tokom vremena jer valjda tako treba
:) , imao sam problema sa stapom pa zbog toga nisam dovoljno obratio paznju
na kretanje kugli a uglove odbijanja cu da sredim i pozicioniranje kamere
veceras.

Pozdrav

2017-01-18 11:46 GMT+01:00 Ivan Čukić <notifications@github.com>:

**Comment by ivan-cukic-matf** [comment]
U redu je da usporavaju, ali mi deluje da čas usporavaju, čas ubrzavaju, i nikad se ne zaustave.

**Comment by chokaa** [comment]
Jer sam stavio da intenzitet bude ogroman jer hocu da doradim da moze i
jacina udarca da se podesi a ovo mi je za testiranje odbijanja veliki
intenzitet i zato se toliko dugo krecu, veceras cu i to da sredim

On Jan 18, 2017 12:05 PM, "Ivan Čukić" <notifications@github.com> wrote:

U redu je da usporavaju, ali mi deluje da čas usporavaju, čas ubrzavaju, i
nikad se ne zaustave.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/MATF-RG16/RG16-046-bilijar/issues/4#issuecomment-273447517>,
or mute the thread

**Comment by chokaa** [comment]
Sredjeno je kretanje loptica detaljno

2017-01-18 12:08 GMT+01:00 Nikola Ilic <allmightyazlan@gmail.com>:

> Jer sam stavio da intenzitet bude ogroman jer hocu da doradim da moze i
> jacina udarca da se podesi a ovo mi je za testiranje odbijanja veliki
> intenzitet i zato se toliko dugo krecu, veceras cu i to da sredim
>
